//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assign7MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeKey { get; set; }
        public Nullable<int> PersonKey { get; set; }
        public System.DateTime EmployeeHireDate { get; set; }
        public Nullable<decimal> EmployeeAnnualSalary { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
